name: check_certificates
author: Arnaud Kientz
email: arnaud@unpeud.info
url: https://github.com/kiarn/ajenti-plugins
version: '0.1'
title: 'Check certificates'
icon: certificate
dependencies:
    - !!python/object:aj.plugins.PluginDependency { plugin_name: core }
resources:
    - resources/js/module.es
    - resources/js/routing.es
    - resources/js/controllers/index.controller.coffee
    - resources/partial/index.html
    - ng:check_certificates
